import Connection

#Підключення до бази даних
connection = Connection.create_connection("postgres", "admin", "root", "localhost", "5432")
cursor = connection.cursor()

try:


    # Додавання помилок
    errors_data = [
        ('1', 'Помилка вводу даних', '2020-12-4', 'Важлива', 'Дані', 'Користувач'),
        ('2', 'Помилка вводу даних', '2020-11-3', 'Критична', 'Розрахунковий алгоритм', 'Тестувальник'),
        ('3', 'Помилка авторизації ', '2021-3-18', 'Незначна', 'Невідома категорія', 'Тестувальник'),
        ('4', 'Проблеми з підключенням', '2023-5-10', 'Критична', 'Інше', 'Користувач'),
        ('5', 'Помилка при збереженні файлу', '2022-1-15', 'Незначна', 'Дані', 'Користувач'),
        ('6', 'Невдала аутентифікація', '2019-8-23', 'Важлива', 'Розрахунковий алгоритм', 'Тестувальник'),
        ('7', 'Помилка зєднання з базою даних', '2018-4-22', 'Критична', 'Дані', 'Користувач'),
        ('8', 'Помилка валідації електронної пошти', '2022-9-2', 'Незначна', 'Інше', 'Користувач'),
        ('9', 'Помилка авторизації користувача', '2023-3-10', 'Важлива', 'Інше', 'Користувач'),
        ('10', 'Невірний формат даних у файлі', '2022-9-11', 'Незначна', 'Розрахунковий алгоритм', 'Тестувальник'),
        ('11', 'Проблеми з підключенням', '2020-8-31', 'Важлива', 'Дані', 'Тестувальник'),
        ('12', 'Невірний формат даних у файлі', '2022-7-15', 'Незначна', 'Інше', 'Користувач'),
        ('13', 'Помилка при збереженні файлу', '2021-5-24', 'Критична', 'Дані', 'Тестувальник'),
        ('14', 'Помилка зєднання з базою даних', '2019-6-22', 'Важлива', 'Невідома категорія', 'Користувач'),
        ('15', 'Помилка авторизації користувача', '2023-9-18', 'Незначна', 'Інше', 'Тестувальник'),
        ('16', 'Невдала аутентифікація', '2024-9-18', 'Важлива', 'Дані', 'Користувач'),
        ('17', 'Проблеми з підключенням', '2018-5-20', 'Незначна', 'Дані', 'Тестувальник'),
        ('18', 'Невірний формат даних у файлі', '2017-7-18', 'Критична', 'Невідома категорія', 'Користувач'),
        ('19', 'Помилка авторизації', '2022-5-18', 'Незначна', 'Невідома категорія', 'Тестувальник'),
        ('20', 'Помилка валідації електронної пошти', '2021-7-18', 'Незначна', 'Інше', 'Користувач'),
    ]

    insert_query = """
    INSERT INTO Log_error (Code_error, Description_error, Date_of_receipt_of_information_about_the_error, Error_level, functionality_categor, Source)
    VALUES (%s, %s, %s, %s, %s, %s)
    ON CONFLICT (Code_error) DO NOTHING
    """

    for record in errors_data:
        cursor.execute(insert_query, record)

    connection.commit()

except Exception as e:
    print(f"Помилка додавання даних таблиці Помилка: {e}")

try:

    # Додавання програмістів
    programmers_data = [
        ('1', 'Іванов', 'Іван', '+380123456789'),
        ('2', 'Пилипишин', 'Микола', '+380123888964'),
        ('3', 'Колянов', 'Дмитро', '+3801234568998'),
        ('4', 'Жигуров', 'Денис', '+38097664321')
    ]

    insert_query = """
    INSERT INTO Programmers (Programmer_Code, Programmer_Last_Name,Programmer_First_Name, Programmer_Phone)
    VALUES (%s, %s, %s, %s)
    ON CONFLICT (Programmer_Code) DO NOTHING
    """

    for record in programmers_data:
        cursor.execute(insert_query, record)

    connection.commit()

except Exception as e:
    print(f"Помилка при додаванні даних до таблиці Programmers: {e}")


cursor.close()
connection.close()
